---
- name: Initialize Office Weather
  hosts: all
  gather_facts: yes
  remote_user: pi
  become: true

  tasks:
    - fail: msg="Exiting! This play requires you to define the 'new_password' variable. Call the command again with --extra-vars "new_password=yoursecret""
      when: new_password is not defined

    - name: Update apt-cache
      apt: update_cache=yes

    - name: Install Libraries
      apt: name={{item}} state=installed
      with_items:
           - python-pip
           - python-dev
           - libyaml-dev

    - name: Install Pip packages
      pip: name={{item}}
      with_items:
           - librato-metrics
           - pyyaml
           - requests

    - name: Copy config to remote
      template: src=config.yaml dest=/home/pi/config.yaml owner=pi

    - name: Copy script to remote
      copy: src=monitor.py dest=/home/pi/monitor.py owner=pi mode="u+x"

    - name: Create cron header for sudo
      cronvar: name="SHELL" value="/bin/bash"

    - name: Create cron header for pi
      cronvar: name="SHELL" value="/bin/bash" user="pi"

    - name: Create cronjob for root
      cron: name="make sensor accessible" job="if [ $(find /dev/hidraw0 -perm a=rw | wc -l) -eq 0 ] ; then chmod a+rw /dev/hidraw0 ; fi"

    - name: Create cronjob for pi
      cron: name="start script" job="/usr/bin/python /home/pi/monitor.py /dev/hidraw0 > /dev/null 2>&1" user="pi"

    - name: Change pi password
      user: name=pi update_password=always password={{ new_password |password_hash('sha512') }}
